name: Continuous Integration - Resuable
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: Code Lint
      #       - run: echo OK
      #         name: Code Build
      - run: npm install
        name: Install NodeJS modules
      - run: echo npm run test:unit
        name: Code Unit Tests
      - run: echo npm run test:integration
        name: Code Integration Tests
      - run: echo /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.devopsnagesha.online:9000 -Dsonar.projectKey=${{ inputs.project_name }} -Dsonar.qualitygate.wait=true
        name: Code Review
      - run: echo OK
        name: Release Software